// Mini-Disclaimer: For educational/experimental use only; no investment advice or affiliation; no third-party compensation; Profit/ProfitDLL © Nelógica; see README & DISCLAIMER.
use serde::{Deserialize, Serialize};
use thiserror::Error;
use tucano_execution::{error::ClientError, IndexError};

/// Represents all errors generated by the execution link.
#[derive(Debug, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Deserialize, Serialize, Error)]
pub enum ExecutionError {
    /// Indicates an invalid execution manager configuration.
    #[error("ExecutionManager config invalid: {0}")]
    Config(String),

    /// Represents an error that occurred whilst mapping exchange-centric data structures into
    /// their indexed counterparts.
    #[error("IndexError: {0}")]
    Index(#[from] IndexError),

    /// Represents all errors produced by an
    /// [`ExecutionClient`](toucan_execution::client::ExecutionClient).
    #[error("{0}")]
    Client(#[from] ClientError),
}
