//! # Gestão de Execução
//!
//! Módulo de roteamento de requisições de execução e gestão de conta em alto nível.
//! Orquestra execução de ordens em múltiplas exchanges mantendo estado e saldos centralizados.
//!
//! ## Componentes Principais
//!
//! ### ExecutionManager
//! - Roteia requisições de execução para a exchange apropriada
//! - Gerencia links de execução por exchange
//! - Processa eventos de conta e atualiza estado
//! - Interface unificada para trading multi‑exchange
//!
//! ### ExecutionBuilder
//! - Configuração ergonômica para montagem multi‑exchange
//! - Suporta conexões live e mock
//! - Inicializa links de execução e canais de comunicação
//!
//! ### Roteamento de Requisições
//! - Distribuição central baseada em exchange e instrumento
//! - Gerência ciclo de vida de ordens entre protocolos distintos
//! - Tratamento de erros e retries para falhas de execução
//!
//! ## Arquitetura
//!
//! ```text
//! ┌─────────────────────────────────────────────────────────────┐
//! │                    EXECUTION LAYER                          │
//! ├─────────────────┬─────────────────┬─────────────────────────┤
//! │ ExecutionManager│ Request Router  │   Account Manager       │
//! │                 │                 │                         │
//! │ • Multi-Exchange│ • Order Routing │ • Balance Tracking      │
//! │   Coordination  │ • Request Queue │ • Event Processing      │
//! │ • State Sync    │ • Error Handling│ • State Replication     │
//! └─────────────────┴─────────────────┴─────────────────────────┘
//!                              │
//! ┌─────────────────────────────┼─────────────────────────────┐
//! │            EXCHANGE CONNECTIONS                          │
//! ├─────────────────────────────┼─────────────────────────────┤
//! │   Binance ←→ WebSocket      │     Kraken ←→ REST API      │
//! │   Coinbase ←→ FIX           │     Custom ←→ Native        │
//! └─────────────────────────────┴─────────────────────────────┘
//! ```
//!
//! ## Exemplo de Uso
//!
//! ```rust
//! use core::execution::{builder::ExecutionBuilder, request::ExecutionRequest};
//!
//! // Monta sistema de execução multi-exchange
//! let execution = ExecutionBuilder::new()
//!     .add_exchange("binance", binance_config)
//!     .add_exchange("kraken", kraken_config)
//!     .build()
//!     .await?;
//!
//! // Processa requisição de execução
//! let request = ExecutionRequest::OpenOrder(order_request);
//! execution.send(request).await?;
//! ```

use crate::{engine::execution_tx::MultiExchangeTxMap, execution::builder::ExecutionHandles};
use data::streams::reconnect;
// Transition note: we purposefully avoid importing alias types (AssetIndex, ExchangeIndex,
// InstrumentIndex) here to demonstrate direct String usage. Other modules may retain
// the aliases for semantic clarity until newtypes are reintroduced.
use execution::AccountEvent; // alias types replaced locally by String
use integration::channel::Channel;
use tucano_markets::exchange::ExchangeId;

/// Provides an execution manager builder for ergonomically initialising multiple execution links
/// to mock and live exchanges.
pub mod builder;

/// Provides an error type that represents all errors that are generated by an execution link.
pub mod error;

/// Per-exchange execution manager that actions order requests from the Engine and forwards back
/// responses.
pub mod manager;

/// Defines an `ExecutionRequest` used by the `Engine` to communicate with an `ExecutionManager`.
pub mod request;

/// Convenient type alias that represents a [`reconnect::Event`] produced by the [`AccountEvent`]
/// stream.
pub type AccountStreamEvent<ExchangeKey = String, AssetKey = String, InstrumentKey = String> =
    reconnect::Event<ExchangeId, AccountEvent<ExchangeKey, AssetKey, InstrumentKey>>;

/// Initialised [`ExecutionBuild`](builder::ExecutionBuild).
///
/// Contains execution component task handles as well as
/// [`ExecutionRequest`](request::ExecutionRequest) and [`AccountStreamEvent`] channels.
#[allow(missing_debug_implementations)]
pub struct Execution {
    pub execution_txs: MultiExchangeTxMap,
    pub account_channel: Channel<AccountStreamEvent>,
    pub handles: ExecutionHandles,
}
