[advisories]
vulnerability = "deny"
unmaintained = "warn"
deprecated = "warn"
yanked = "deny"
notice = "warn"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[licenses]
unlicensed = "deny"
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-DFS-2016",
  "Zlib"
]
copyleft = "warn"
deny = []
confidence-threshold = 0.8

[licenses.private]
ignore = true
