[package]
name = "tucano-risk"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/brbtavares/tucano"
description = "Interfaces e implementações de gestão de risco para o ecossistema Tucano"
keywords = ["trading","risk","risk-management","finance"]
categories = ["finance","algorithms"]

[dependencies]
"tucano-execution" = { workspace = true }
"tucano-markets" = { workspace = true }
serde = { version = "1", features = ["derive"] }
rust_decimal = { version = "1", features = ["serde"] }
derive_more = { version = "1", features = ["constructor", "display", "from"] }
thiserror = "2"
