[package]
name = "tucano-examples"
version = "0.1.0"
edition = "2021"

[features]
# Placeholder feature to allow conditional compilation in examples
real_dll = []

[dependencies]
"tucano-markets" = { path = "../markets" }
profitdll = { path = "../profitdll" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
rand = { workspace = true }
chrono = { workspace = true }

[[bin]]
name = "validate_b3_execution"
path = "validate_b3_execution.rs"

[[bin]]
name = "profit_dll_b3_integration"
path = "profit_dll_b3_integration.rs"

[[bin]]
name = "profit_dll_windows_config"
path = "profit_dll_windows_config.rs"

# [[bin]]
# name = "simple_trading_strategy"
# path = "simple_trading_strategy.rs"

[[bin]]
name = "basic_b3_usage"
path = "basic_b3_usage.rs"
