[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[dependencies]
# Toucan ecosystem
analytics = { path = "../analytics" }
core = { path = "../core" }
data = { path = "../data" }
execution = { path = "../execution" }
integration = { path = "../integration" }
macros = { path = "../macros" }
markets = { path = "../markets" }
risk = { path = "../risk" }
strategy = { path = "../strategy" }

# External dependencies commonly used in examples
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
futures = "0.3"
futures-util = "0.3"
tokio-stream = "0.1"
rust_decimal = "1.0"
rust_decimal_macros = "1.0"
derive_more = "0.99"
smol_str = "0.1"
itertools = "0.10"
reqwest = { version = "0.11", features = ["json"] }
thiserror = "1.0"
hmac = "0.12"
sha2 = "0.10"
tokio-tungstenite = { version = "0.20", features = ["native-tls"] }

# Core examples
[[bin]]
name = "engine_async_with_historic_market_data_and_mock_execution"
path = "src/bin/engine_async_with_historic_market_data_and_mock_execution.rs"

[[bin]]
name = "engine_sync_with_audit_replica_engine_state"
path = "src/bin/engine_sync_with_audit_replica_engine_state.rs"

[[bin]]
name = "engine_sync_with_live_market_data_and_mock_execution_and_audit"
path = "src/bin/engine_sync_with_live_market_data_and_mock_execution_and_audit.rs"

[[bin]]
name = "engine_sync_with_risk_manager_open_order_checks"
path = "src/bin/engine_sync_with_risk_manager_open_order_checks.rs"

# Data examples
[[bin]]
name = "dynamic_multi_stream_multi_exchange"
path = "src/bin/dynamic_multi_stream_multi_exchange.rs"

[[bin]]
name = "indexed_market_stream"
path = "src/bin/indexed_market_stream.rs"

[[bin]]
name = "multi_stream_multi_exchange"
path = "src/bin/multi_stream_multi_exchange.rs"

[[bin]]
name = "order_books_l1_streams"
path = "src/bin/order_books_l1_streams.rs"

[[bin]]
name = "order_books_l1_streams_multi_exchange"
path = "src/bin/order_books_l1_streams_multi_exchange.rs"

[[bin]]
name = "order_books_l2_manager"
path = "src/bin/order_books_l2_manager.rs"

[[bin]]
name = "order_books_l2_streams"
path = "src/bin/order_books_l2_streams.rs"

[[bin]]
name = "public_trades_streams"
path = "src/bin/public_trades_streams.rs"

[[bin]]
name = "public_trades_streams_multi_exchange"
path = "src/bin/public_trades_streams_multi_exchange.rs"

# Execution examples
[[bin]]
name = "binance_client_example"
path = "src/bin/binance_client_example.rs"
