[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[dependencies]
# Toucan ecosystem
analytics = { path = "../analytics" }
core = { path = "../core" }
data = { path = "../data" }
execution = { path = "../execution" }
integration = { path = "../integration" }
macros = { path = "../macros" }
markets = { path = "../markets" }
risk = { path = "../risk" }
strategy = { path = "../strategy" }

# External dependencies commonly used in examples
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
futures-util = "0.3"
rust_decimal = "1.0"
rust_decimal_macros = "1.0"
derive_more = "0.99"
smol_str = { workspace = true }
itertools = "0.10"
reqwest = { version = "0.11", features = ["json"] }
hmac = "0.12"
sha2 = "0.10"
tokio-tungstenite = { workspace = true }
http = "1.3.1"
dotenv = "0.15.0"
hex.workspace = true

# Examples organized by category

# Binance Integration Examples
[[bin]]
name = "binance_api_authenticated_request"
path = "src/bin/binance_api_authenticated_request.rs"

[[bin]]
name = "binance_btc_realtime_statistics"
path = "src/bin/binance_btc_realtime_statistics.rs"

[[bin]]
name = "binance_client_example"
path = "src/bin/binance_client_example.rs"

[[bin]]
name = "binance_orderbook_level1_streaming"
path = "src/bin/binance_orderbook_level1_streaming.rs"

[[bin]]
name = "binance_orderbook_level2_streaming"
path = "src/bin/binance_orderbook_level2_streaming.rs"

[[bin]]
name = "binance_public_trades_streaming"
path = "src/bin/binance_public_trades_streaming.rs"

[[bin]]
name = "binance_websocket_basic_integration"
path = "src/bin/binance_websocket_basic_integration.rs"

# Trading Engine Examples
[[bin]]
name = "trading_engine_historical_data_simulation"
path = "src/bin/trading_engine_historical_data_simulation.rs"

[[bin]]
name = "trading_engine_live_data_with_audit"
path = "src/bin/trading_engine_live_data_with_audit.rs"

[[bin]]
name = "trading_engine_multiple_strategies"
path = "src/bin/trading_engine_multiple_strategies.rs"

[[bin]]
name = "trading_engine_paper_trading_simulation"
path = "src/bin/trading_engine_paper_trading_simulation.rs"

[[bin]]
name = "trading_engine_risk_management"
path = "src/bin/trading_engine_risk_management.rs"

# Backtesting Examples
[[bin]]
name = "trading_backtesting_concurrent_strategies"
path = "src/bin/trading_backtesting_concurrent_strategies.rs"

# Multi-Exchange Examples
[[bin]]
name = "multi_exchange_synchronized_streaming"
path = "src/bin/multi_exchange_synchronized_streaming.rs"

[[bin]]
name = "order_books_l1_streams_multi_exchange"
path = "src/bin/order_books_l1_streams_multi_exchange.rs"

[[bin]]
name = "public_trades_streams_multi_exchange"
path = "src/bin/public_trades_streams_multi_exchange.rs"

# Advanced Data Processing Examples
[[bin]]
name = "dynamic_multi_stream_multi_exchange"
path = "src/bin/dynamic_multi_stream_multi_exchange.rs"

[[bin]]
name = "indexed_market_stream"
path = "src/bin/indexed_market_stream.rs"

[[bin]]
name = "order_books_l2_manager"
path = "src/bin/order_books_l2_manager.rs"

# System Examples
[[bin]]
name = "engine_sync_with_audit_replica_engine_state"
path = "src/bin/engine_sync_with_audit_replica_engine_state.rs"
