# Exemplo de configuração para cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[licenses]
# Lista de licenças permitidas
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]

[bans]
# Crates que não devem ser usadas
deny = [
    # Crates descontinuadas
    { name = "stdweb", reason = "use wasm-bindgen instead" },
]

# Permitir múltiplas versões temporariamente
multiple-versions = "warn"

[sources]
# Fontes permitidas para dependências
unknown-registry = "warn"
unknown-git = "warn"

[advisories]
# Configuração para vulnerabilidades de segurança
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
